LoomSDK/LoomSDK

loom/engine/bindings/loom/lmApplication.cpp, loom/engine/sound/lsSound.cpp
This prevents sounds bleeding into the next reload and fixed background soundtrack stacking of sounds (super annoying).
=> Fixed sounds not being unloaded on code reload, now sounds are destroyed

tools/assetAgent/src/main.cpp
If a file gets created and deleted very quickly, the live reloading asset system can pick up the creation, but then spams the console output when it can't find it anymore, since it was deleted.
This can happen very quickly when exporting with Audacity, since it creates and deletes a file named [filename]0.ogg before moving/deleting it, making the console continuously output the following, since the file doesn't get removed from the pending files list.
```
[loom.asset]    o Skipping due to not being in the asset folder!
[loom.asset] Failed to resolve path .\assets/laser0.ogg via realpath due to No such file or directory
[loom.asset]    o Skipping due to not being in the asset folder!
[loom.asset] Failed to resolve path .\assets/laser0.ogg via realpath due to No such file or directory …
```
=> Fixed reload when a file gets added and deleted in rapid succession

sdk/src/loom2d/Math/Rectangle.ls
i've put together ad hoc tests to ensure the intersects method is still functioning as expected, and they [show speed ups of about 28%](https://github.com/LoomSDK/LoomSDK/commit/7012e6b#commitcomment-7861575):
* [baseline](https://github.com/ellemenno/LoomSDK/tree/PBG-rect-intersect-baseline/tests/RectangleIntersectsTest)
* [improved](https://github.com/ellemenno/LoomSDK/tree/PBG-rect-intersect-sat/tests/RectangleIntersectsTest)
..but i haven't been able to figure out how to get the loomlibs rejiggered to allow proper unit testing:
http://loomsdk.com/forums/feedback/topics/unittest-framework-for-loomscript/posts/5230
=> simplify rectangle separation test to improve performance

loom/script/native/core/system/lmDebug.cpp, sdk/src/system/Debug.ls
... to allow call stack info to be retrieved from anywhere in a LS app
=> Added getCallStack to Debug

docs/examples/RobotLegs/src/org/robotlegs/base/CommandMap.ls, loom/script/native/core/system/Reflection/lmType.cpp, loom/script/reflection/lsAssembly.cpp, loom/script/reflection/lsType.cpp, loom/script/reflection/lsType.h, sdk/src/system/Reflection/Type.ls, sdk/src/test/TestReflection.ls
This changes the `getMethodInfo` signature and semantics, the new name is `getMethodInfoByName` which is now consistent with other methods.
=> Added method info count and retrieval by index

application/windows/main.cpp, loom/engine/bindings/loom/lmApplication.cpp, loom/script/native/core/system/lmProcess.cpp, loom/script/native/core/system/lmProcess.h, loom/vendor/openal-soft/Alc/ALc.c
Included are also fixes for shutdown cleanup, better support for direct LoomDemo execution with console on Windows and removal of OpenAL message complaining about having to cleanup resources on shutdown.
=> Fixed LoomDemo to allow argument passing and console on Windows to work.

loom/common/platform/platformTime.c
... to actually report time from app start and not break everything after the time overflows and/or wraps.
=> Fixed platform_getMilliseconds() / Platform.getTime() on Windows

loom/engine/loom2d/l2dDisplayObjectContainer.cpp, loom/engine/loom2d/l2dDisplayObjectContainer.h, loom/graphics/gfxVectorRenderer.cpp
... and additionally removed unnecessary OpenGL state modification breaking stuff when an empty Shape was added to the stage
=> Fixes default clipping issues (popped up in FeathersComponentExplorer)

sdk/src/feathers/controls/ScreenNavigator.ls
Bug Fixed:
- Fixed a backwards logical assessment that would cause null to be
returned when getScreen is called with a valid ID, and cause a crash
when getScreen is called with an invalid ID
=> Screen Navigator Fix

.gitignore, docs/examples/NanoVG/src/NanoVG.ls, loom/engine/loom2d/l2dScript.cpp, loom/engine/loom2d/l2dStage.h, loom/graphics/gfxVectorGraphics.cpp, loom/graphics/gfxVectorRenderer.cpp, loom/graphics/gfxVectorRenderer.h, loom/vendor/stb/stb_truetype.h, sdk/src/loom/Application.ls, sdk/src/loom2d/Display/Stage.ls
- Fixes NanoVG debug mode (it's now only turned on #if GFX_OPENGL_CHECK), this should avoid expensive glGetError calls.
- Fixes a bug in stb_truetype I spotted while doing a C++ analysis on the project (it still has many alike that we could address).
- Adds a square box reload indicator (by default disabled). We should do better before enabling by default I think.
- Also added bin-release example dirs to gitignore
=> Various fixes with NanoVG / truetype / reload

application/common/core.cpp, loom/common/platform/platformAndroidJni.cpp
A bugfix for SQLiteExample and a touch event bug that affected touch based devices.
=> 2 bugfixes

loom/common/core/performance.cpp, loom/common/core/performance.h, loom/engine/bindings/loom/lmApplicationTasks.cpp, loom/script/runtime/lsProfiler.cpp
… and removed the faulty loom_tick block as the dump happens within it
Also tested random START/END calls and the only one that fell through was having a START with no END (stack overflow gets caught, but it's possible to not overflow before dumping/reset), which now gets caught with the zero stack check before dumping.
=> Added profiler zero stack check

loom/common/utils/utCommon.h, loom/engine/bindings/loom/lmModestMaps.cpp, loom/engine/loom2d/l2dDisplayObject.h, loom/engine/loom2d/l2dMatrix.h, loom/engine/loom2d/l2dQuad.cpp, loom/engine/loom2d/l2dQuadBatch.cpp, loom/engine/loom2d/l2dQuadBatch.h, loom/engine/loom2d/l2dRectangle.h, loom/graphics/gfxGraphics.cpp, loom/graphics/gfxMath.h, loom/graphics/gfxVectorGraphics.cpp, loom/graphics/gfxVectorGraphics.h, loom/graphics/gfxVectorRenderer.cpp, loom/graphics/gfxVectorRenderer.h, loom/script/native/lsLuaBridge.h, sdk/src/loom/ModestMaps/core/TileGrid.ls
Moved float to typedef floating point tfloat (now double) matrices, transforms, display object properties to avoid 32-bit inaccuracy in apps (like mapping)
=> Floating point change + better maps positionTiles

loom/graphics/CMakeLists.txt, loom/graphics/gfxQuadRenderer.cpp, loom/graphics/gfxStateManager.c, loom/graphics/gfxStateManager.h, loom/vendor/nanovg/src/nanovg_lm_gl.h
This removes some  "cleanup" that the two renderers were doing, so
they can reuse the state they set up before.
Additionally, some whitespace errors are fixed.
This is a crude implementation, but it works. Maybe it could be improved further when other issues are resolved (QuadRenderer batching bug for ex.).
=> Simple GL state managment implementation

loom/engine/bindings/loom/lmHTTPRequest.cpp, sdk/src/loom/HTTPRequest.ls
Improvements:
- Added a flag to HTTPRequest that indicates if a request is pending
- If the HTTPRequest object is cleaned up while a request is pending, a
user friendly warning is produced
=> HTTP cleanup warning

build/win-cmake.bat
Added a fallback to check default Visual Studio paths in case required registry keys are missing.
=> Fallback if VS registry keys are missing

docs/examples/ScriptBenchmark/src/BenchmarkAllocation.ls, docs/examples/ScriptBenchmark/src/BenchmarkFieldAccess.ls, docs/examples/ScriptBenchmark/src/BenchmarkFunctionCall.ls, docs/examples/ScriptBenchmark/src/ScriptBenchmark.ls, loom/engine/loom2d/l2dQuad.cpp, loom/engine/loom2d/l2dQuadBatch.cpp, loom/graphics/CMakeLists.txt, loom/graphics/gfxQuadRenderer.cpp, loom/graphics/gfxQuadRenderer.h, loom/script/compiler/lsJitTypeCompiler.cpp, loom/script/compiler/lsJitTypeCompiler.h, loom/script/compiler/lsTypeCompiler.cpp, loom/script/compiler/lsTypeCompiler.h, loom/script/compiler/lsTypeCompilerBase.cpp, loom/script/compiler/lsTypeCompilerBase.h, loom/script/native/core/system/lmBaseDelegate.cpp, loom/script/native/core/system/lmConsole.cpp, loom/script/native/core/system/lmObject.cpp, loom/script/native/lsLuaBridge.h, loom/script/native/lsNativeInterface.cpp, loom/script/native/lsNativeInterface.h, loom/script/reflection/lsMethodInfo.cpp, loom/script/reflection/lsType.cpp, loom/script/reflection/lsType.h, loom/script/runtime/lsClassRT.cpp, loom/script/runtime/lsInstanceRT.cpp, sdk/src/loom2d/Display/DisplayObjectContainer.ls, sdk/src/test/tests/TestManagedNativeClass.ls
Added allocation benchmark. 10k allocations went from 335ms to 200ms avg time on 2.6ghz MacBook Pro (Retina, 13-inch, Mid 2014).
Constructors now call their own supers.
Instance initializer blocks are also now part of constructor, but are also kept separately for use when wrapping natives.
Tweaked script instance memory allocation to achieve better performance (on OSX).
Type now caches many frequently called queries to avoid massive data structure traversals during object construction.
Console::Log now avoids memory allocation.
Tested with JIT and Classic Lua.
=> Constructor Optimizations

loom/engine/loom2d/l2dScript.cpp, loom/graphics/gfxVectorGraphics.cpp, loom/graphics/gfxVectorGraphics.h
... which fixes an alignment crash on Android
=> Made getBounds return a Rectangle allocated on heap

loom/engine/loom2d/l2dStage.cpp
Maybe it's useful for some cases so gl doesn't randomly decide when to process commands, though this call might be ignored by some drivers?
=> Do we want glFInish?

loom/engine/bindings/loom/lmGameController.cpp
getGameController method no longer returns `null` if trying to access a controller that is not connected. An assert was added to make sure controller index is not too high.
=> getGameController no longer returns `null`

loom/script/runtime/lsLuaState.cpp
dumpLuaTable outputs fewer levels of logs
=> dumpLuaTable outputs fewer levels of logs

build/Swarley
This along with the build box fix should make docs work, tested with `loom docs`, can't test `loom new` without firehose or implementing custom sdks.
=> Docs path fix

sdk/src/loom/ModestMaps/Map.ls, sdk/src/loom/ModestMaps/overlays/ImageMarker.ls, sdk/src/loom/ModestMaps/overlays/MarkerClip.ls
Fixed a few Modest Maps crashes regarding markers and added `onZoom` and `onRender` rigging for proper marker updating.
Apparently also removed unnecessary whitespace... thanks FlashDevelop!
=> Fixed modest maps crashes and some event rigging

loom/common/assets/assets.cpp, loom/common/platform/platformFile.c, loom/common/platform/platformFile.h, loom/common/platform/platformIO.c, loom/script/native/core/system/Platform/lmFile.cpp, sdk/src/loom2d/Textures/Texture.ls, sdk/src/system/Platform/File.ls, tools/assetAgent/src/main.cpp
Fixed platform_normalizePath so it's thread safe .. or more accurately so that the caller is responsible for safety
Added platform_moveFile and File.move that pretty much just map to the rename syscall
Fixed some copy pasted comments in platformFile.h
Added more canonical file exists for windows because I thought that was the problem and why not
Fixed so texture caching first downloads to a .part file and then renames when finished for better reliability
=> Fixed map caching along with some related functionality and added File.move

loom/script/compiler/lsJitTypeCompiler.cpp
Apparently this addition of `twoSlotFrameInfo` broke nested `for each` loops.
=> Fix for the `for each` loop on ARM 64

loom/script/compiler/lsTypeCompilerBase.cpp
Assignment mode had to be reset after first compile (most platforms) for the second compile (ARM64) to build properly. This fixes Location Example problem on iOS.
=> Fixed `++` operator working with setters correctly on ARM 64

application/common/core.cpp, loom/common/platform/platformMobileIOS.mm, loom/engine/bindings/loom/lmApplication.cpp, loom/engine/bindings/loom/lmApplicationTasks.cpp
Switched from didEnterBackground to willEnterBackground as that seems like the more proper place as per Apple docs
Now pausing app while camera is open (fixes GL breaking after camera closes)
gLoomTicking is now a counter to allow for multiple pause/resume calls properly pausing and resuming
=> A bunch of camera semi-related fixes

sdk/src/feathers/controls/Button.ls, sdk/src/feathers/controls/TextInput.ls
Reverted `Event.CHANGE` from Button's `currentState` setter, since it breaks a bunch of stuff. There is already a CHANGE event in `isSelected` and there's also an `Event.TRIGGERED`
Reworked TextInput's focus code so it only clears focus when you click outside (and not when you just hover outside)
=> Reverted breaking Button change, fixed TextInput focus

application/common/core.cpp
We need to ignore CapsLock and NumLock modifiers when checking for backspace.
=> Fix for backspace input

Rakefile, build/Swarley, docs/main.rb
After landing, the following steps shouldn't fail anymore:
* `loom new MyThrusties --example Thrusties --firehose`
* should download the latest firehose (this branch after it gets landed and built)
* should create a new example dir called MyThrusties and copy the Thrusties example from firehose into it
* `cd MyThrusties` and `loom run` should run the example successfully (loom.config, assets and source should all be present for this to work)
=> Add back example files needed for `loom new`

application/android/AndroidManifest.xml
We already compiled for sdk 15, but it wasn't declared as such in the manifest
=> Fixed the Android three dots appearing on the bottom right

Rakefile, build/libs/helper.rb
When deploying an SDK, rake now complains about files it can't delete and retries for a while, then fails. This is a lot better than silently skipping files it can't overwrite, leading to you running out of date builds, which can be very frustrating and demotivational.
=> Way better dev workflow using dev builds and deploying often
