LoomSDK/LoomSDK

loom/common/platform/platformNetwork.c

My branch with some C fixes over the LFL one.

Replace 'gethostbyname' with 'getaddrinfo' as the former is now deprecated

---

Rakefile

Primarily a build server issue but a couple of code fixes helped.

Fix for iOS builds.

---

loom/script/native/core/system/Reflection/lmAssembly.cpp
loom/script/native/lsNativeInterface.cpp
loom/script/reflection/lsAssembly.cpp
loom/script/reflection/lsAssembly.h
loom/script/runtime/lsLuaState.cpp
loom/script/runtime/lsLuaState.h
loom/script/serialize/lsBinReader.cpp
sdk/src/system/Reflection/Assembly.ls

Seems like the system doesn't like it somewhere down the line, possibly due to it expecting to be at the top of the lua stack - needs investigation!
Don't :airplane: yet!

Added Assembly.loadBytes

---

loom/common/assets/assets.cpp
loom/common/assets/assets.h
loom/script/native/core/assets/lmAssets.cpp
loom/script/native/lsNativeDelegate.cpp
loom/script/native/lsNativeDelegate.h
sdk/src/loom/LoomBinaryAsset.ls

Probably only works for zips right now.

Added LoomBinaryAsset for live reloading binary assets

---

CMakeLists.txt
LICENSE_THIRDPARTY
Rakefile
loom/graphics/gfxMath.h
loom/graphics/gfxVectorGraphics.cpp
loom/graphics/gfxVectorGraphics.h
loom/graphics/gfxVectorRenderer.cpp
loom/graphics/gfxVectorRenderer.h
loom/vendor/nanovg/src/nanovg.c
loom/vendor/sdl2/include/SDL_config.h.cmake

SDL2 with Windows (static), OS X (system) and Android (static prebuilt)

---

loom/graphics/gfxTexture.cpp

The previous one was failing on odd width images and possibly had other anomalies.

Added better downsampling methods

---

docs/examples/ClipRectExample/loom.config
docs/examples/ClipRectExample/src/ClipRectExample.ls
loom/engine/loom2d/l2dShape.cpp
loom/engine/loom2d/l2dShape.h
loom/graphics/gfxVectorGraphics.cpp
loom/graphics/gfxVectorGraphics.h
loom/graphics/gfxVectorRenderer.cpp
loom/vendor/nanovg/src/nanovg.c
loom/vendor/nanovg/src/nanovg.h
sdk/src/loom2d/Display/Shape.ls

nanovg now clips properly in the clip hierarchy

Integrated NanoVG clipping into the rest of the display tree

---

loom/common/platform/platformHttpAndroid.cpp

Because of local class references not being deleted.

Fixed crashing in Modest Maps

---

docs/guides/02_LoomScript/05_profiling.md
loom/common/core/performance.cpp
loom/common/core/performance.h
loom/engine/loom2d/l2dStage.cpp
loom/graphics/gfxQuadRenderer.cpp
loom/graphics/gfxVectorGraphics.cpp
loom/graphics/gfxVectorRenderer.cpp
sdk/src/loom/Application.ls

Changed onCocosFrame to onInternalFrame
Changed hardcoded 0.1 supression value into a variable
Fixed LOOM_PROFILE_SCOPE
Added additional profiling blocks for various stages of rendering

Minor profiler fixes and better renderer profiling

---

application/android/src/co/theengine/loomdemo/LoomHTTP.java
application/ouya/src/co/theengine/loomdemo/LoomDemo.java
docs/examples/ModestMapsExample/src/ModestMapsExample.ls
loom/common/assets/assets.cpp
loom/common/core/log.h
loom/common/platform/platformAndroidJni.cpp
loom/engine/bindings/loom/lmApplication.cpp
loom/engine/bindings/loom/lmModestMaps.cpp
loom/engine/loom2d/l2dRectangle.h
loom/graphics/gfxTexture.cpp
loom/graphics/gfxVectorGraphics.cpp
loom/graphics/gfxVectorGraphics.h
loom/script/runtime/lsClassRT.cpp
loom/script/runtime/lsLuaState.cpp
loom/vendor/jemalloc-3.4.0/include/jemalloc/jemalloc_defs.h
sdk/src/loom/ModestMaps/Map.ls
sdk/src/loom/ModestMaps/core/Tile.ls
sdk/src/loom/ModestMaps/core/TileGrid.ls
sdk/src/loom/ModestMaps/core/TwoInputTouch.ls
sdk/src/loom/ModestMaps/core/painter/TilePainter.ls
sdk/src/loom/ModestMaps/core/painter/TilePool.ls
sdk/src/loom2d/Core/TouchProcessor.ls
sdk/src/loom2d/Events/TouchEvent.ls
sdk/src/loom2d/Textures/Texture.ls

Added better Android http printing.
Better / fixed allocation in vector graphics.
Disabled jemalloc debug.
Better tile loading / handling / hopefully fewer bugs.

Modest maps and various other fixes

---

sdk/src/loom/LML/ILMLNode.ls
sdk/src/loom/LML/LMLDocument.ls
sdk/src/loom/LML/LMLNode.ls
sdk/src/loom/Utils/Injector.ls

(Git seems to have also fixed some CRLF inconsistencies that weren't visible until I pushed)

LML Injection fixes from patch

---

loom/common/core/performance.h
loom/vendor/luajit/src/lj_gc.c

For now the step and fullgc functions. Seems pretty stable, but needs a switch that makes the calls disappear to avoid overhead before landing I think.

Added general profiling of internal luajit garbage collection

---

loom/script/native/core/system/lmString.cpp
sdk/src/test/tests/TestString.ls

Everything seems to be in order.

Applied patch WindowsHexStringToNumberFix.patch

---

sdk/src/loom2d/Events/TouchEvent.ls

Bug Fixes:
- Fixed an crash in the TouchEvent caused by natively deleted objects

Input Crash Fix

---

sdk/src/loom/Application.ls
sdk/src/system/Random.ls

Improvements:
- Made the Random Number generator (Random) automatically seed to the
Epoch time at application startup

Automatic Seeding

---

loom/engine/bindings/loom/lmApplication.cpp

Bug Fixes:
- Fixed an issue causing loom sound to not be initialized properly

Jje sound fix

---

application/common/core.cpp
loom/engine/bindings/loom/lmApplication.cpp
loom/graphics/gfxGraphics.cpp
loom/vendor/sdl2/src/render/opengl/SDL_render_gl.c
sdk/src/loom/Graphics/Graphics.ls

Improvements:
- Re-Added screenshot support

SDL Screenshots

---

loom/script/native/core/system/Platform/lmFile.cpp
loom/script/native/core/system/lmProfiler.cpp
loom/script/runtime/lsLuaState.cpp
loom/script/runtime/lsProfiler.cpp
loom/script/runtime/lsProfiler.h
sdk/src/loom/Application.ls
sdk/src/system/Profiler.ls

Changed Profiler.enable(bool) to Profiler.enable/disable

---

sdk/src/loom/HTTPRequest.ls

Improvements:
- Minor doc update, added delegate return info

HTTPRequest Doc Update

---

loom/common/platform/platformHTTPCurl.cpp

Tested with http://httpbin.org/put (http://httpbin.org/)

Added Curl PUT support for uploading through HTTP

---

docs/examples/ModestMapsExample/src/LandmarkViewer.ls
sdk/src/loom/ModestMaps/extras/Distance.ls

Hey, here's something we forgot!

Basic cleanup and docs for landmark viewer™ and distance

---

loom/vendor/nanosvg/src/nanosvg.h
loom/vendor/nanosvg/src/nanosvgrast.h

Fixes Roomlia SVG rendering issues.

nanosvg update from upstream

---

loom/graphics/gfxGraphics.cpp

Improvements:
- Made memory management improvements
- Made fixes that should help screenshots on Android

Screenshot Fixes

---

loom/graphics/gfxGraphics.cpp

Remove redundant code and simplify syntax. Consistent indentation.

Cleanup in aisle gfxGraphics.cpp.

---

loom/graphics/gfxStateManager.c

Fixed NanoVG not rendering

---

docs/examples/NanoVG/loom.config
loom/graphics/gfxGraphics.cpp

and changed nanovg example from dev to latest

Fixed warning / better error

---

loom/engine/loom2d/l2dQuad.cpp
loom/engine/loom2d/l2dQuadBatch.cpp
loom/graphics/CMakeLists.txt
loom/graphics/gfxQuadRenderer.cpp
loom/graphics/gfxQuadRenderer.h

Removed multiple vertex buffers.
Added sub-state managment to QuadRenderer.
Refactored for consistence and redability.

QuadRenderer optimizations & refactor

---

build/win-cmake.bat

Modified Visual Studio version detection to detect from registry key and not default install locations.

Detect Visual Studio version from registry

---

loom/graphics/gfxVectorGraphics.cpp
loom/graphics/gfxVectorRenderer.cpp
loom/graphics/gfxVectorRenderer.h

SVG and texture fill now support global alpha

Full alpha support in vector graphics

---

loom/script/native/core/system/lmDate.cpp
loom/script/native/core/system/lmPackageSystem.cpp
sdk/src/system/Date.ls

New Features:
- Added a simple date class with a single function that exposes the
strftime functon to Loom
**Needs to be tested on the following platforms:**

Basic Date Class

---

Rakefile

Improvements:
- Completely removed Ouya building to avoid errors
Will the build bot build it? That is the question

Ouya Removal

---

loom/script/native/core/system/lmDate.cpp
sdk/src/system/Date.ls
sdk/src/test/tests/DateTest.ls

New Features:
- Added better date functionality

More Complete Date Utility

---

loom/common/assets/assets.cpp
loom/common/assets/assets.h
loom/common/assets/assetsImage.c
loom/common/core/allocator.c
loom/common/core/allocator.h
loom/common/core/stringTable.c
loom/common/utils/utByteArray.h
loom/common/utils/utString.cpp
loom/engine/bindings/loom/lmApplication.cpp
loom/engine/loom2d/l2dScript.cpp
loom/engine/loom2d/l2dShape.h
loom/graphics/gfxTexture.cpp
loom/graphics/gfxTexture.h
loom/graphics/gfxVectorRenderer.cpp
loom/script/native/core/system/lmRandom.cpp
loom/script/native/core/system/lmString.cpp
loom/script/native/core/test/lmTestManagedNative.cpp
loom/script/native/core/test/lmTestNativeClass.cpp
loom/script/native/lsLuaBridge.h
loom/script/native/lsNativeInterface.cpp
loom/script/native/lsNativeInterface.h
loom/script/reflection/lsType.cpp
loom/vendor/nanovg/src/fontstash.h
loom/vendor/nanovg/src/nanovg.c

Moved STBI implementation definition into assetImage.c instead of it being in nanovg, set STBI to use loom alloc
Replaced crazy pants string read/write code in utByteArray with existing fromBytes method (getting rid of an allocation)
Fixed a bunch of new calls to be lmNew calls
Implemented custom allocators for nanovg and fontstash and mapped them to loom alloc
Moved lua bridge from system to loom alloc
Fixed some strings funcs to alloc properly (they probably shouldn't alloc at all?)

Various memory related fixes

---

loom/script/native/core/system/Platform/lmPlatform.cpp
sdk/src/system/Platform/Platform.ls
sdk/src/test/tests/PlatformTest.ls

New features:
- Added a Platform.sleep function that wraps loom_thread_sleep

Platform Sleep

---

loom/graphics/gfxBitmapData.cpp
loom/graphics/gfxBitmapData.h

My goal is to fix this enough for my meeting tomorrow. I am fully open to nicer fixes.

Adjust types to see if we can fix runtime error no Mac.

---

loom/graphics/gfxTexture.cpp

… for the case when the textureinfo gets disposed, but the threadNote is still around (happened to me while live-reloading)

Added a check to async texture loading

---

loom/graphics/gfxGraphics.cpp
loom/graphics/gfxQuadRenderer.cpp

Looks like we were culling too much and not invalidating enough! :)

GL state fixes for render texture functionality

---

docs/examples/CacheAsBitmapExample/loom.config
docs/examples/CacheAsBitmapExample/src/CacheAsBitmapExample.ls
loom/engine/loom2d/l2dDisplayObject.cpp
loom/engine/loom2d/l2dDisplayObject.h
loom/engine/loom2d/l2dDisplayObjectContainer.cpp
loom/engine/loom2d/l2dDisplayObjectContainer.h
loom/engine/loom2d/l2dShape.cpp

Wait for #419 to land
Still haven't checked all of the bounds to see if any of them can break, however in general you should be fine either way if you have a background drawn first and then stuff on top of it.

cacheAsBitmap for vector graphics

---

loom/common/utils/guid.cpp
loom/common/utils/guid.h
loom/script/native/core/system/Utils/lmSystemUtilsPackage.cpp
sdk/src/system/Utils/GUID.ls

Added a workaround for Android, verified it works.

A simple GUID utility

---

loom/common/core/allocator.h
loom/common/xml/tinyxml2.cpp
loom/common/xml/tinyxml2.h
loom/engine/loom2d/l2dQuad.cpp
loom/script/native/lsLuaBridge.h

This works on iOS and OSX, will test on Win/Android and then we can land after JG-ColorFix

Mem Alignment fix for iOS crash

---

build/cmake/loom.artifacts.cmake
loom/script/compiler/lsCompiler.cpp
tools/lsc/src/main.cpp

Added a "project" parameter to lsc to indicate the root of the project to compile

Fix the meaning of Root to mean the SDK dir

---

loom/engine/loom2d/l2dDisplayObjectContainer.cpp
loom/graphics/gfxGraphics.cpp
loom/graphics/gfxGraphics.h
loom/graphics/gfxVectorGraphics.cpp

Fixed clip rect issues

---

sdk/src/feathers/controls/Button.ls

Improvements:
- Added public read access to the Feathers Button `currentState` property
- The Feathers Button now dispatches a CHANGE event whenever the
currentState property is altered

Button State Access

---

build/libs/targets.rb
build/libs/toolchains.rb

This fixes VS detection (at least on my machine)

Reverted some VS detection

---

application/common/core.cpp

Seems to work fine on Windows and Android. Should be fine elsewhere too.

Handle Application Gain/Loose focus events

---

build/libs/targets.rb
build/libs/toolchains.rb

Not a 100% sure if this will work for other people, if not we'll have to do some checking which arch name is supported.

Fixes build on some windows configurations

---

loom/script/runtime/lsLuaState.cpp

Reverts LoomSDK/LoomSDK#452
Maybe we do still need this... I'll test this like 3 times on (OSX) build box and if none of them fail I think it's good to land at least as a hotfix until we figure out wtf is going on.

Revert "We don't need this anymore I think"

---

loom/script/runtime/lsClassRT.cpp

Better table preallocation for objects, less wasted space

---

loom/script/compiler/lsParser.cpp
sdk/src/loom2d/Display/Graphics.ls

Added docs generation for enums and extended some text alignment comments.

Docs generation fix

---

loom/script/native/core/system/lmGC.cpp
loom/script/runtime/lsLuaState.cpp

... and an out of memory warning

Slightly better gc behavior in some circumstances

---

loom/script/compiler/lsJitTypeCompiler.cpp

Changed the way results of tail calls are returned.

Fixed a crash caused by the compiler

---

.gitignore
Rakefile

Added examples .app to gitignore
Added sdl2 to rake clean (to avoid much frustration)

Build tweaks

---

Rakefile
build/libs/toolchains.rb

Also fixed a bug in rakefile when detecting vcvarsall there

Added vcvarsall checks in toolchains

---

loom/common/core/performance.cpp
loom/common/core/performance.h
loom/script/runtime/lsClassRT.cpp
loom/script/runtime/lsProfiler.cpp

This resolves all of the issues Mark was having.

Fixes for profiler stability

---

loom/common/core/performance.cpp
loom/common/core/performance.h
loom/common/platform/platformTime.c

Profiling/debug stuff now seems to work as expected on all supported platforms

Made the unix timing code less prone to overflow

---

loom/engine/loom2d/l2dRectangle.h
loom/engine/loom2d/l2dScript.cpp
loom/vendor/stb/stb_vorbis.c

Fixes a couple of memory leaks that popped up while investigating with Dr. Memory

Fix a couple of memory leaks

---

docs/examples/TimerTest/.gitignore
docs/examples/TimerTest/loom.config
docs/examples/TimerTest/src/TimerTest.ls
sdk/src/loom/Platform/Timer.ls
sdk/src/unittest/TestRunner.ls

Due to Timer not being available in loomexec, I had to make it into an example like UserDefaultTest.
Additionally fixed a few things I found while making the test.
Depends on #569

TimerTest and a few fixes
